blank_issues_enabled: true
contact_links:
  - name: Steam
    url: https://steamcommunity.com/id/arminc/
    about: You can get help on custom topics.
  - name: E-Mail
    url: mailto:arminandrey@gmail.com
    about: Official inquiries.